### ISSUE TITLE
DICOMDIR files (Media Storage Directory Storage SOP Class) cannot be compressed!

### ISSUE THREAD

**Issue by HimanshuN** [InsightSoftwareConsortium/DCMTK#1]
While running "dcmcjpeg +tl dicom_compression/06822MRSMANJUMUJUMDAR75.dcm dic.dcm" command on raw dicom image I am getting this error. I am trying to compress this image. Can anyone help please. Waiting for reply

**Comment by thewtex** [comment]
You may need to enable OpenJPEG support in your DCMTK build.
