### ISSUE TITLE
error (Invalid Value) parsing file: SRc.xxx.yyy.zzz

### ISSUE THREAD

**Issue by tommydino93** [InsightSoftwareConsortium/DCMTK#2]
Hello :)
I am having issues converting a dsr file into xml using _**dsr2xml**_

When running from command line:

```
cd path_to_folder_containing_dsr_file
dsr2xml SRc.my.report.file test.xml
```
I get the following warnings/errors:

```
W: PerformedProcedureCodeSequence (0040,a372) absent in SRDocumentGeneralModule (type 2)
W: StudyInstanceUID (0020,000d) absent in CurrentRequestedProcedureEvidenceSequence (type 1)
W: Reading unknown/unsupported CompletionFlag (COMPLETED)
W: PersonName (0040,a123) empty in content item (type 1)
W: Reading invalid/incomplete content item PNAME "1.3"
E: Reading content item PNAME "1.3" (Invalid Value)
F: dsr2xml: error (Invalid Value) parsing file: SRc.my.report.file
```
Any suggestions on how to fix this?

Thank you very much in advance!

**Comment by malaterre** [comment]
@tommydino93 This is not the location where you should post DCMTK issue. There is a forum at: https://forum.dcmtk.org/

@jriesmeier

**Comment by jriesmeier** [comment]
As @malaterre pointed out, there is a public DCMTK forum where you could post your question. It seems that your sample SR violates the definitions of the DICOM standard in multiple ways.

**Comment by tommydino93** [comment]
Apologies! Thank you very much
